spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/Dion
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: Dion
    password: Dion1234!

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update